### ISSUE TITLE
can't turn it off!

### ISSUE THREAD

**Issue by jjmaldonis** [Maxymillion/zen#1]
Hello! I like your plugin but I'm having one major issue. I can't turn focus mode off! Luckily I use the Ctrl+, shortcut to open Obsidian's settings, so I can disable the plugin and that turns off focus mode.

I can click the button to turn focus mode on, but when I try to click the button to turn it off it simple doesn't do anything. The icon is there, but it isn't clickable.

I've tried on both a windows desktop and laptop. I don't have other UI plugins installed that would be interacting with the UI.

**Comment by Maxymillion** [comment]
@jjmaldonis thanks for your Message. Could you open the Developer console (ctrl + shift + i) and tell me what error it throws?

**Comment by jjmaldonis** [comment]
There aren't any error messages in the console unfortunately.

![image](https://user-images.githubusercontent.com/2326898/219102235-1f894a4a-e54e-434b-b2e5-232191f7ba7e.png)

You can see from the screen this is the case. My mouse is also hovered over the /eye/ icon in the top left (which you can't see), but the cursor is a normal cursor and not a hand as is typical for a button. The icon is just unclickable.

When I open the inspect tools, I can't hover over the /eye/ icon. The div/html element for the icon doesn't even show up in the DOM (I'm looking for it in the `workspace-tab-header-container` element), even tho it's on my screen. See the screenshots below:

![image](https://user-images.githubusercontent.com/2326898/219104470-3cad5068-5d08-463b-8d90-ed4e0979d22c.png)
![image](https://user-images.githubusercontent.com/2326898/219104596-0001a75f-4e35-4549-ac98-2c257767540f.png)

**Comment by jjmaldonis** [comment]
Disabling the command palette plugin doesn't have any effect.

**Comment by Maxymillion** [comment]
@jjmaldonis Thank you for your feedback, it seems the element is behind the header element. I'll implement a fix for that and let's test it again.

**Comment by Maxymillion** [comment]
I'll fix this issue tonight and send a message when I've implemented a fix!

**Comment by jjmaldonis** [comment]
Great thanks! I'm looking forward to using it.

In my plugin, I use a method called `<HTMLElement>.replaceChildrenInPlace([... child nodes])` to manually edit the DOM. It should be possible to grab the `workspace-tab-header-container` HTML element, and do something like:

```
const existingTabHeaderChildren = <workspace-tab-header-container>.children;
<workspace-tab-header-container>.replaceChildrenInPlace([yourZenButtonHTMLElement, ...existingTabHeaderChildren]);
```

and actually insert your Zen button into the existing HTML/DOM.

I have no idea if this is practical for your plugin, but it might be worth 10 minutes of your time. This method has worked well for me in the plugin I created (called Audio Notes).

And thanks!!

**Comment by Maxymillion** [comment]
@jjmaldonis, thanks a lot! It does exist in the DOM but not the location you think haha. What I'm doing is creating a leaf (like a pinned page would be) but not displaying it's content. So I can have a movable button in the left top. But when enabling the plugin it should be moved (the button) (to the main header from the sidebar) but at the time I thought this (using a "css trick" to pop the button out of the overflow of the main element) would suffice... Sadly it didn't, I'll do it the proper way. 
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/7950495/219107822-46527cfe-285f-4ba8-9f10-7a3883ab0f9c.png">

**Comment by Maxymillion** [comment]
@jjmaldonis, I've fixed the issue and it should be working quite a bit better right now.

**Comment by jjmaldonis** [comment]
Works like a charm now!
