### ISSUE TITLE
Add an config to also go into full screen

### ISSUE THREAD

**Issue by kaleidawave** [Maxymillion/zen#7]
Often when I go into zen mode I also want Obsidian to go into full screen. Would be great under a config to for the zen mode command to trigger that (and on escape leave fullscreen).

I think it is possible using [requestFullScreen](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen)

**Comment by Maxymillion** [comment]
Sorry for the late replay, but I would love to implement this. I'll try to add it in the next release!
