### ISSUE TITLE
I don't like the button in the left side bar

### ISSUE THREAD

**Issue by tagg-lee** [Maxymillion/zen#8]
![CleanShot 2023-05-21 at 13 49 49](https://github.com/Maxymillion/zen/assets/115551695/532cdd19-fd08-4337-9bb5-b02dc9bc5cc1)

**Comment by Maxymillion** [comment]
Hi @tagg-lee, in version 0.6.5 you're able to hide the button ❤️

**Comment by tagg-lee** [comment]
Thank you for the update!
